#include <arm_neon.h>
class DataGenerator
{
private:
    int n_samples, n_features;
    int max_label;
    bool generated;
    void generate(int i_start, int i_end, float16_t max_value);
    void deallocateMemory();
    int thread_count;

public:
    float16_t **data;
    int *labels;
    DataGenerator();
    void GenerateData(int n_samples, int n_features, float16_t max_value, int max_label); // floats are generated by default
    ~DataGenerator();
};